title: Adam Brendgard
author: GitHub User
email: adam@brendgard.tech
description: > # this means to ignore newlines until "baseurl:"
  Cybersecurity professional

# social links
twitter_username: adambrendgard # DO NOT include the @ character, or else the build will fail!
github_username:  adambrendgard # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
